### ISSUE TITLE
Password auth failed

### ISSUE THREAD

**Issue by skrzepto** [fedora-infra/faitout#7]
When I request the path for postgres and try to connect it keeps throwing this error.

```
E       OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "ucpnt0uddGygEhwqXjG9"

```

**Comment by pypingou** [comment]
How long after requesting the session? And after how many session were opened?

**Comment by skrzepto** [comment]
It was immediately after requesting the session lets say 1 min from requesting to trying to connect.

I assume only 1 session was active I was timed out an hour before this issue came occured so I assume those connections were automatically dropped.

**Comment by skrzepto** [comment]
I'll try it again tonight and see if the issue persists

**Comment by skrzepto** [comment]
Still getting the issue issue but I think its got to do with something on my side, I'll modify the code and see investigate my hunch.

**Comment by skrzepto** [comment]
Seems to work in a small example. I'll close as its most likely on my end
